# Generated by Django 3.2.9 on 2021-11-19 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Суть вопроса')),
                ('text', models.TextField(verbose_name='Ваш вопрос')),
                ('question_status', models.CharField(blank=True, choices=[('Рассмотрено', 'Рассмотрено'), ('На рассмотрении', 'На рассмотрении'), ('Приостановлено', 'Приостановлено')], default='На рассмотрении', max_length=20, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор вопроса')),
            ],
        ),
    ]
